Repository brain-tec/odoo-formio, pull requests merged in 2023-03, with the labels that each got.

#42 Syncing from upstream novacode-nl/odoo-formio (14.0)
  formio/models/ir_actions.py
Labels: 14.0

#43 Syncing from upstream novacode-nl/odoo-formio (15.0)
  formio/models/ir_actions.py
Labels: 15.0

#44 Syncing from upstream novacode-nl/odoo-formio (14.0)
  formio/CHANGELOG.md
  formio/__manifest__.py
  formio/views/formio_menu.xml
Labels: 14.0

#45 Syncing from upstream novacode-nl/odoo-formio (15.0)
  formio/CHANGELOG.md
  formio/__manifest__.py
  formio/views/formio_menu.xml
Labels: 15.0

#47 Syncing from upstream novacode-nl/odoo-formio (15.0)
  formio/CHANGELOG.md
  formio/__manifest__.py
  formio/controllers/main.py
  formio/controllers/portal.py
  formio/controllers/public.py
  formio/models/formio_builder.py
  formio/models/ir_actions.py
  formio/views/formio_menu.xml
Labels: 15.0

#48 Merge 15.0 into 15.0.project_PR_449
  formio/CHANGELOG.md
  formio/__manifest__.py
  formio/controllers/main.py
  formio/controllers/portal.py
  formio/controllers/public.py
  formio/models/formio_builder.py
  formio/models/ir_actions.py
  formio/views/formio_builder_views.xml
  formio/views/formio_menu.xml
  formio/views/ir_actions_views.xml
Labels: 15.0.project_pr_449

#49 Syncing from upstream novacode-nl/odoo-formio (15.0)
  formio/static/description/index.html
Labels: 15.0
