Repository brain-tec/odoo-formio, pull requests merged in 2023-02, with the labels that each got.

#29 Syncing from upstream novacode-nl/odoo-formio (14.0)
  formio/models/formio_version.py
Labels: 14.0

#30 Syncing from upstream novacode-nl/odoo-formio (15.0)
  formio/models/formio_version.py
Labels: 15.0

#31 Test dummy version fix
  formio/models/formio_version.py
Labels: 15.0.20220130_testupdate

#32 Syncing from upstream novacode-nl/odoo-formio (15.0)
  formio/CHANGELOG.md
  formio/__manifest__.py
  formio/models/__init__.py
  formio/models/formio_builder.py
  formio/models/ir_actions.py
  formio/views/formio_builder_views.xml
  formio/views/ir_actions_views.xml
Labels: 15.0

#33 Syncing from upstream novacode-nl/odoo-formio (15.0)
  formio/CHANGELOG.md
  formio/__manifest__.py
  formio/controllers/portal.py
  formio/controllers/public.py
  formio/models/formio_builder.py
  formio/models/ir_actions.py
  formio/static/src/js/form/formio_form.js
Labels: 15.0

#34 Merge 15.0 into PR_449 project branch
  formio/CHANGELOG.md
  formio/__manifest__.py
  formio/controllers/portal.py
  formio/controllers/public.py
  formio/models/__init__.py
  formio/models/formio_builder.py
  formio/models/ir_actions.py
  formio/static/src/js/form/formio_form.js
  formio/views/formio_builder_views.xml
  formio/views/ir_actions_views.xml
Labels: 15.0.project_pr_449

#35 Syncing from upstream novacode-nl/odoo-formio (15.0)
  formio/CHANGELOG.md
  formio/__manifest__.py
  formio/models/formio_version.py
  formio/models/ir_actions.py
  formio/views/formio_builder_views.xml
  formio/views/ir_actions_views.xml
Labels: 15.0

#37 Syncing from upstream novacode-nl/odoo-formio (15.0)
  formio/CHANGELOG.md
  formio/__manifest__.py
  formio/models/formio_version.py
  formio/views/ir_actions_views.xml
Labels: 15.0

#38 Syncing from upstream novacode-nl/odoo-formio (14.0)
  formio/models/ir_actions.py
  formio_purchase/models/purchase.py
Labels: 14.0

#39 Syncing from upstream novacode-nl/odoo-formio (15.0)
  formio/models/ir_actions.py
Labels: 15.0

#40 Syncing from upstream novacode-nl/odoo-formio (14.0)
  formio/CHANGELOG.md
  formio/__manifest__.py
  formio/models/ir_actions.py
  formio/views/ir_actions_views.xml
Labels: 14.0

#41 Syncing from upstream novacode-nl/odoo-formio (15.0)
  formio/CHANGELOG.md
  formio/__manifest__.py
  formio/models/ir_actions.py
  formio/views/ir_actions_views.xml
Labels: 15.0
